services:
  app:
    build: .
    tty: true
    container_name: mercadata_api
    volumes:
      - ./app:/app:cached
    working_dir: /app
    ports:
      - "9999:8000"
    env_file:
      - .env

  mongodb:
    image: mongo:latest
    container_name: mercadata_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data: