services:
  app:
    build: .
    tty: true
    container_name: app_py
    volumes:
      - ./app:/app:cached
    working_dir: /app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DB_URL_MERCADATA=${DB_URL_MERCADATA}
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=${VIRTUAL_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - FRONTEND_URL=${FRONTEND_URL}
    networks:
      - proxy
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mercadata_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always
    networks:
      - proxy

volumes:
  mongodb_data:

networks:
  proxy:
    external: true
