services:
  app:
    build: .
    tty: true
    container_name: app_py
    volumes:
      - ./app:/app:cached
    working_dir: /app
    ports:
      - "80:80"
    environment:
      - PYTHONUNBUFFERED=1
